[[files]]
name = "rustc/binutils-2.44.tar.xz"
source = "https://ftp.gnu.org/gnu/binutils/binutils-2.44.tar.xz"
sha256 = "ce2017e059d63e67ddb9240e9d4ec49c2893605035cd60e92ad53177f4377237"
license = "GNU General Public License"

[[files]]
name = "rustc/gcc-8.4.0.tar.xz"
source = "https://ftp.gnu.org/gnu/gcc/gcc-8.4.0/gcc-8.4.0.tar.xz"
sha256 = "e30a6e52d10e1f27ed55104ad233c30bd1e99cfb5ff98ab022dc941edd1b2dd4"
license = "GNU General Public License"
