# Demo file to ensure the tooling works :D
[[files]]
name = "bors-r-plus.png"
source = "https://www.pietroalbini.org/bors-r-plus.png"
sha256 = "2d58773aebf52adcc8917e914d77bcd0315719f39baf5c22a26e9dcae6be71d9"
license = "Pietro created it at some point I guess"
